### ISSUE TITLE
No output in the history

### ISSUE THREAD

**Issue by caedmon-kitty** [tokenizer/xontrib-output-search#3]
I have 6xonsh/0.9.27.  I have installed and loaded -
xontrib list output_search                                                    
output_search  installed      loaded
I tried the examples from the README and nothing happens when I type Alt-F nor f__<tab> for any of the examples.

Are there any additional steps I need to take in order to get output_search to work.

**Comment by anki-code** [comment]
Hi @caedmon-kitty !
Could you please tell us your OS and the `xonfig` command output.

**Comment by caedmon-kitty** [comment]
Fedora version 33
⇨ __xonsh__.history[-1]                                                         
HistoryEntry(cmd='echo 1\n', out=None, rtn=0, ts=[1618953179.0237632, 1618953179.0373187])

⇨ printenv|fgrep SHELL_TYPE                                                  
SHELL_TYPE=prompt_toolkit

I have a two line prompt if that matters
<CWD> @ <HOSTNAME>                                                      
⇨ 
example:
~ @ localhost.domain                                                      
⇨

**Comment by anki-code** [comment]
> out=None

Here should be `out='1\n'`. 

Try to run:
```
# Open bash
xonsh --no-rc
xontrib load output_search
echo 1
__xonsh__.history[-1]
# HistoryEntry(cmd='echo 1\n', out='1\n', ...
```
Do you have appropriate `out` variable? If no post your `xonfig` output.

**Comment by caedmon-kitty** [comment]
xonsh --no-rc
user@local ~ $ xontrib load output_search
user@local ~ $ echo 1
1
user@local ~ $ __xonsh__.history[-1]
HistoryEntry(cmd='echo 1\n', out='1\n', rtn=0, ts=[1619048632.4105785, 1619048632.4266448])
user@local ~ $

It works with --no-rc.  I will try adding my .xonshrc one line at a time and see if I can isolate the offending config item.

**Comment by caedmon-kitty** [comment]
It looks like the xontrib-bashisms xontrib is the culprit.  Removing that and now output_search works for me.  Yea!

**Comment by anki-code** [comment]
Ah, yeah, bashisms is the xontrib that I recommend to avoid. Many unexpected issues around this xontrib. Instead of trying to bring bash into xonsh I recommend to dive into xonsh by reading [xonsh-cheatsheet](https://github.com/anki-code/xonsh-cheatsheet/blob/main/README.md).

**Comment by anki-code** [comment]
If you like the xontrib-output-search please star the repo. Thanks!

**Comment by patricknraanes** [comment]
Thanks for all your awesome work! I'm having a similar issue:

    user@local:~$ xonsh --no-rc
    ... [welcome message]
    user@local ~ $ xontrib load output_search
    user@local ~ $ echo 1
    1
    user@local ~ $ __xonsh__.history[-1]
    HistoryEntry(cmd='echo 1\n', out=None, rtn=0, ts=[1631863878.775298, 1631863878.792896], cwd='/home/AD.DOMAIN.NO/user')

I'm on Ubuntu 20.04.

**Comment by anki-code** [comment]
Hi @patricknraanes! Please check the known issue - [Not working after xonsh 0.10.0 (4283)](https://github.com/tokenizer/xontrib-output-search#not-working-after-xonsh-0100-4283)
